name: After Tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Match tags starting with 'v'

jobs:
  after_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run after tag
        run: |
          echo "This step will run after a tag is created."
          echo github.head_ref ${{ github.head_ref }}
          echo github.ref ${{ github.ref }}
          echo github.ref_name ${{ github.ref_name }}            

          - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install databricks-cli
              pip install dbx --upgrade
              databricks --version
              dbx --version
          
          - name: Run Databricks CLI commands
            env:
              DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
              DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
            run: |
              echo $DATABRICKS_HOST
              databricks configure --token
              echo $DATABRICKS_TOKEN | databricks workspace ls /Repos
    