name: Release Workflow
on:
  release:
    types:
      - published

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Run after release is published
        run: |
          echo "This step will run after a release is published"
          echo github.head_ref ${{ github.head_ref }}
          echo github.ref ${{ github.ref }}
          echo github.ref_name ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli
          pip install dbx --upgrade
          databricks --version
          dbx --version
          
      - name: Run Databricks CLI commands
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo $DATABRICKS_TOKEN > token-file
          databricks configure --host $DATABRICKS_HOST --token-file token-file
          rm -f token-file
          databricks workspace ls /Repos
          databricks repos update --path "/Repos/Staging/tech-summit-clone" --tag ${{ github.ref_name }} 
