name: Release Workflow
on:
  release:
    types:
      - published

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Run after release is published
        run: |
          echo "This step will run after a release is published"
          echo github.head_ref ${{ github.head_ref }}
          echo github.ref ${{ github.ref }}
          echo github.ref_name ${{ github.ref_name }}
