name: Merge Action

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run your custom script
        run: |
          # Put your script commands here
          echo "Custom script after merge"
